In [2]:
import pandas as pd
df = pd.read_csv('./data/HR.csv')
df.head(10)

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   
5                0.41             0.50               2                    153   
6                0.10             0.77               6                    247   
7                0.92             0.85               5                    259   
8                0.89             1.00               5                    224   
9                0.42             0.53               2                    142   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   
5                   3              0     1                      0      sales   
6                   4              0     1                      0      sales   
7                   5              0     1                      0      sales   
8                   5              0     1                      0      sales   
9                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low  
5     low  
6     low  
7     low  
8     low  
9     low

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
type(df['satisfaction_level'])

pandas.core.series.Series

In [5]:
df.mean()

satisfaction_level         0.612839
last_evaluation           67.373732
number_project             3.802693
average_monthly_hours    201.041728
time_spend_company         3.498067
Work_accident              0.144581
left                       0.238235
promotion_last_5years      0.021264
dtype: float64

In [6]:
type(df.mean())

pandas.core.series.Series

In [7]:
df['satisfaction_level'].mean()

0.6128393333333333

In [9]:
#中位数
df.median()

satisfaction_level         0.64
last_evaluation            0.72
number_project             4.00
average_monthly_hours    200.00
time_spend_company         3.00
Work_accident              0.00
left                       0.00
promotion_last_5years      0.00
dtype: float64

In [10]:
df['satisfaction_level'].median

<bound method Series.median of 0        0.38
1        0.80
2        0.11
3        0.72
4        0.37
         ... 
14997    0.11
14998    0.37
14999     NaN
15000     NaN
15001    0.70
Name: satisfaction_level, Length: 15002, dtype: float64>

In [11]:
df['satisfaction_level'].median()

0.64

In [12]:
#分位数
df.quantile(q=0.25)

satisfaction_level         0.44
last_evaluation            0.56
number_project             3.00
average_monthly_hours    156.00
time_spend_company         3.00
Work_accident              0.00
left                       0.00
promotion_last_5years      0.00
Name: 0.25, dtype: float64

In [13]:
#下四分位数
df['satisfaction_level'].quantile(q=0.25)

0.44

In [14]:
#众数
df.mode()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                 0.1             0.55             4.0                    135   
1                 NaN              NaN             NaN                    156   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                 3.0            0.0   0.0                    0.0      sales   
1                 NaN            NaN   NaN                    NaN        NaN   

  salary  
0    low  
1    NaN

In [15]:
df['department'].mode()

0    sales
dtype: object

In [16]:
#标准差
df['satisfaction_level'].std()

0.24862338135944925

In [17]:
#方差
df['satisfaction_level'].var()

0.061813585758606134

In [18]:
#求和
df['satisfaction_level'].sum()

9192.59

In [19]:
type(df['satisfaction_level'])

pandas.core.series.Series

In [20]:
type(df.var())

pandas.core.series.Series

In [21]:
#偏态系数
df['satisfaction_level'].skew()

-0.47643761717258093

In [22]:
#峰态
df['satisfaction_level'].kurt()

-0.6706959323886252

In [24]:
pip install scipy

In [25]:
#生成正态分布
import scipy.stats as ss
ss.norm

In [26]:
#m-均值，v-方差，s-标准差，k-峰态系数
ss.norm.stats(moments='mvsk')

(array(0.), array(1.), array(0.), array(0.))

In [27]:
ss.norm.pdf(0.0)

0.3989422804014327

In [29]:
ss.norm.ppf(0.9)

1.2815515655446004

In [30]:
#正两倍的标准差减去负两倍的标准差
ss.norm.cdf(2)-ss.norm.cdf(-2)

0.9544997361036416

In [31]:
#得到10个符合正态分布的数字
ss.norm.rvs(size=10)

array([-0.99944845, -0.62620307,  0.5386933 ,  0.88195572,  2.03237594,
        1.94033737, -0.0146241 ,  1.07295758,  0.60475225, -1.64624971])

In [32]:
#卡方分布
ss.chi2

In [33]:
#t分布
ss.t

In [34]:
#f分布
ss.f

In [35]:
#抽样10个
df.sample(10)

satisfaction_level  last_evaluation  number_project  \
8330                 0.51             0.54               4   
7615                 0.90             0.79               3   
9598                 0.79             0.72               5   
14164                0.48             0.72               3   
13289                0.69             0.88               3   
12492                0.11             0.83               6   
5687                 0.52             0.77               4   
8338                 0.81             0.62               5   
1254                 0.38             0.49               2   
6068                 0.94             0.97               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
8330                     166                   4              1     0   
7615                     222                   6              1     0   
9598                     245                   3              1     0   
14164                    143                   4              0     0   
13289                    164                  10              0     0   
12492                    244                   4              0     1   
5687                     134                   4              0     0   
8338                     201                   3              1     0   
1254                     144                   3              0     1   
6068                     221                   2              0     0   

       promotion_last_5years  department  salary  
8330                       0       sales     low  
7615                       0   technical  medium  
9598                       0   technical     low  
14164                      0       sales  medium  
13289                      0  management  medium  
12492                      0          hr  medium  
5687                       0   technical     low  
8338                       0       sales  medium  
1254                       0          hr     low  
6068                       0   technical  medium

In [36]:
#frac百分比0.001
df.sample(frac=0.001)

satisfaction_level  last_evaluation  number_project  \
2956                 0.85             0.79               3   
14738                0.09             0.90               7   
7697                 0.91             0.55               2   
849                  0.54             0.94               6   
4832                 0.74             0.99               5   
8754                 0.66             0.69               3   
2107                 0.59             0.88               4   
10962                0.65             0.79               5   
2200                 0.89             0.53               5   
4336                 0.72             0.67               5   
3132                 0.50             0.73               3   
7063                 0.80             0.52               3   
4531                 0.93             0.96               5   
10902                0.76             0.92               3   
257                  0.42             0.54               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
2956                     157                   4              0     0   
14738                    289                   4              0     1   
7697                     234                   2              0     0   
849                      294                   3              0     1   
4832                     146                   2              0     0   
8754                     257                   2              0     0   
2107                     155                   3              1     0   
10962                    233                   3              0     0   
2200                     272                   3              0     0   
4336                     219                   3              0     0   
3132                     148                   3              0     0   
7063                     182                   2              0     0   
4531                     135                   3              1     0   
10902                    176                   2              0     0   
257                      156                   3              0     1   

       promotion_last_5years   department  salary  
2956                       0      support  medium  
14738                      0  product_mng     low  
7697                       0           IT     low  
849                        0        sales  medium  
4832                       0        sales     low  
8754                       0      support  medium  
2107                       0      support     low  
10962                      0      support     low  
2200                       0           IT     low  
4336                       0           IT     low  
3132                       0   accounting     low  
7063                       0    technical  medium  
4531                       0        sales     low  
10902                      0           IT  medium  
257                        0        sales  medium

In [ ]:
#分布分析
import numpy as np
import pandas as pd
df= pd.read_csv('./data/HR.csv')
#异常值分析
sl_s=df['satisfaction_level']

In [38]:
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [40]:
#看共有几条异常值
sl_s[sl_s.isnull()]

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [41]:
#查看含这两条异常值的具体的数据格式
df[df['satisfaction_level'].isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [42]:
#丢弃
sl_s=sl_s.dropna()

In [44]:
#画图,分布间隔0.1
np.histogram(sl_s.values,bins=np.arange(0.0,1.1,0.1))

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [45]:
#静态结构分析
le_s=df['last_evaluation']
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

In [46]:
le_s.mean()

67.37373216904412

In [47]:
le_s.std()

8164.407523745649

In [48]:
le_s.median()

0.72

In [49]:
le_s.skew()

122.48265175204614

In [50]:
le_s.max()

999999.0

In [51]:
le_s.min()

0.36

In [52]:
le_s.kurt()

15001.999986807796

In [54]:
le_s[le_s>1]

15000    999999.0
Name: last_evaluation, dtype: float64

In [55]:
le_s[le_s<=1]

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [56]:
#四分位间距
le_s = df['last_evaluation']
q_low = le_s.quantile(q=0.25)
q_high = le_s.quantile(q=0.75)
q_interval = q_high - q_low
k = 1.5
le_s = le_s[le_s<q_high+k*q_interval][le_s>q_low-k*q_interval]
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [57]:
np.histogram(le_s.values,bins=np.arange(0.0,1.1,0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [58]:
np_s=df['number_project']
np_s[np_s.isnull()]

Series([], Name: number_project, dtype: int64)

In [59]:
#数这些属性出现多少次
np_s.value_counts()

4    4365
3    4055
5    2761
2    2391
6    1174
7     256
Name: number_project, dtype: int64

In [60]:
#比列组成
np_s.value_counts(normalize=True)

4    0.290961
3    0.270297
5    0.184042
2    0.159379
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [61]:
#对上述结果排序
np_s.value_counts(normalize=True).sort_index()

2    0.159379
3    0.270297
4    0.290961
5    0.184042
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [3]:
#分布分析_average_monthly_hours
import numpy as np
import pandas as pd
df= pd.read_csv('./data/HR.csv')
amh_s=df['average_monthly_hours']

In [4]:
amh_s.mean()

201.0417277696307

In [5]:
amh_s.std()

49.94181527437925

In [6]:
amh_s.max()

310

In [7]:
amh_s.min()

96

In [8]:
amh_s.skew()

0.05322458779916304

In [9]:
amh_s.kurt()

-1.1350158577565719

In [10]:
#去除异常值
amh_s=amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]
len(amh_s)

15002

In [11]:
#np.histogram(amh_s.values,bins=10)，bins左闭右开
np.histogram(amh_s.values,bins=np.arange(amh_s.min(),amh_s.max()+10,10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86],
       dtype=int64),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316], dtype=int64))

In [12]:
#计算连续值的数量,bins左开右闭
amh_s.value_counts(bins=np.arange(amh_s.min(),amh_s.max()+10,10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

In [13]:
#time_spend_company
tsc_s=df['time_spend_company']
tsc_s.value_counts().sort_index()

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

In [14]:
#salary
s_s=df['salary']
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

In [15]:
s_s.where(s_s=='nme')

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
14997    NaN
14998    NaN
14999    NaN
15000    NaN
15001    nme
Name: salary, Length: 15002, dtype: object

In [17]:
#去除nme异常值
s_s.where(s_s!='nme').dropna().value_counts()

low       7318
medium    6446
high      1237
Name: salary, dtype: int64

In [18]:
#department
d_s=df['department']
d_s.value_counts(normalize=True)

sales          0.275963
technical      0.181309
support        0.148647
IT             0.081789
product_mng    0.060125
marketing      0.057192
RandD          0.052460
accounting     0.051127
hr             0.049260
management     0.041994
sale           0.000133
Name: department, dtype: float64

In [22]:
#去除sale异常值
d_s.where(d_s!='sale').dropna().value_counts()

sales          4140
technical      2720
support        2230
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [25]:
#1.对比分析--先去掉所有异常值
df=df.dropna(axis=0,how='any')
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14995                    160                   3              0     1   
14996                    143                   3              0     1   
14997                    280                   4              0     1   
14998                    158                   3              0     1   
15001                    158                   2              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  
15001                      0       sale     nme  

[15000 rows x 10 columns]

In [26]:
df=df[df['last_evaluation']<=1][df['salary']!='nme'][df['department']!='sale']

d:\chen\biancheng\jupytertest\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [27]:
#2对比分析-各部门对比
df.groupby('department').mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294

In [28]:
df.loc[:,['last_evaluation','department']].groupby('department')

In [29]:
df.loc[:,['last_evaluation','department']].groupby('department').mean()

last_evaluation
department                  
IT                  0.716830
RandD               0.712122
accounting          0.717718
hr                  0.708850
management          0.724000
marketing           0.715886
product_mng         0.714756
sales               0.709717
support             0.723109
technical           0.721099

In [30]:
#极差
df.loc[:,['average_monthly_hours','department']].groupby('department')['average_monthly_hours'].apply(lambda x:x.max()-x.min())


department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64