##5特征工程

In [2]:
import pandas as pd
df = pd.DataFrame({"A": ["a0", "a1", "a1", "a2", "a3", "a4"], "B": ["b0", "b1", "b2", "b2", "b3", None],
                       "C": [1, 2, None, 3, 4, 5], "D": [0.1, 10.2, 11.4, 8.9, 9.1, 12], "E": [10, 19, 32, 25, 8, None],
                       "F": ["f0", "f1", "g2", "f3", "f4", "f5"]})
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [3]:
df.isnull()

A      B      C      D      E      F
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False   True  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False   True  False  False   True  False

In [4]:
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [5]:
#去掉空值,所有含有空值的都去掉
df.dropna()

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

In [6]:
#只想去掉某一行空值
df.dropna(subset=['B'])

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
2  a1  b2  NaN  11.4  32.0  g2
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

In [7]:
#识别A的重复值
df.duplicated(['A'])

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [8]:
#只有A和B同时重复才是重复的
df.duplicated(['A','B'])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [9]:
#去除重复值
df.drop_duplicates(['A'])

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [11]:
#keep-可选择保留的重复值,可选first,last,False
df.drop_duplicates(['A'],keep=False)

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [12]:
#标注异常值
df.fillna('b*')

A   B   C     D   E   F
0  a0  b0   1   0.1  10  f0
1  a1  b1   2  10.2  19  f1
2  a1  b2  b*  11.4  32  g2
3  a2  b2   3   8.9  25  f3
4  a3  b3   4   9.1   8  f4
5  a4  b*   5  12.0  b*  f5

In [13]:
#使用均值代替E的异常值
df.fillna(df['E'].mean())

A     B     C     D     E   F
0  a0    b0   1.0   0.1  10.0  f0
1  a1    b1   2.0  10.2  19.0  f1
2  a1    b2  18.8  11.4  32.0  g2
3  a2    b2   3.0   8.9  25.0  f3
4  a3    b3   4.0   9.1   8.0  f4
5  a4  18.8   5.0  12.0  18.8  f5

In [14]:
#对E插值，注意插值方法只用于series
df['E'].interpolate()

0    10.0
1    19.0
2    32.0
3    25.0
4     8.0
5     8.0
Name: E, dtype: float64

In [15]:
pd.Series([1,None,4,5,20]).interpolate()
#返回相邻两值的平均值，如果在末尾，取前面的数，如在第一个看后面的数

0     1.0
1     2.5
2     4.0
3     5.0
4    20.0
dtype: float64

In [16]:
#样条插值
df['E'].interpolate(method='spline',order=3)

0    10.000000
1    19.000000
2    32.000000
3    25.000000
4     8.000000
5   -20.143603
Name: E, dtype: float64

In [18]:
#对D通过四分位间距取异常值
upper_q=df['D'].quantile(0.75)
lower_q=df['D'].quantile(0.25)
q_int=upper_q-lower_q
k=1.5
df[df['D']>lower_q-k*q_int][df['D']<upper_q+k*q_int]

d:\chen\biancheng\jupytertest\venv\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


A     B    C     D     E   F
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [19]:
#去掉F列的异常值
df.drop(2)

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [20]:
df[[True if item.startswith('f') else False for item in list(df['F'].values)]]

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

##特征选择

In [23]:
import numpy as np
import pandas as pd
import scipy.stats as ss
#ABC正态分布，D随机分布
df=pd.DataFrame({'A':ss.norm.rvs(size=10),'B':ss.norm.rvs(size=10),'C':ss.norm.rvs(size=10),'D':np.random.randint(low=0,high=2,size=10)})
df

A         B         C  D
0 -0.796890 -0.335036  0.070946  0
1  0.029701  0.395473  0.612565  1
2  0.195781 -1.083136 -0.407007  0
3  0.226145 -1.367649  1.280285  0
4  0.012025 -0.747287  1.230495  0
5 -0.060997  0.358104 -0.557926  1
6  0.941274  1.601609  0.480859  1
7  0.019985  0.067739 -0.076426  0
8  1.400832  2.287839  0.211201  1
9 -0.121079  0.434613 -3.320969  1

In [24]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
#分别引入特征选择，包裹，嵌入思想的方法
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel
#引入特征
X=df.loc[:,['A','B','C']]
#引入标注
Y=df.loc[:,'D']
skb=SelectKBest(k=2) #过滤思想
skb.fit(X,Y)

SelectKBest(k=2, score_func=<function f_classif at 0x0000018F7F1EC6A8>)

In [25]:
skb.transform(X)

array([[-0.79688961, -0.33503619],
       [ 0.02970131,  0.39547298],
       [ 0.19578143, -1.0831359 ],
       [ 0.22614539, -1.36764927],
       [ 0.01202528, -0.74728732],
       [-0.06099681,  0.35810436],
       [ 0.94127421,  1.60160901],
       [ 0.01998544,  0.06773894],
       [ 1.40083197,  2.28783927],
       [-0.1210788 ,  0.43461304]])

In [26]:
#线性回归拟合，挑选2个特征，每次一步
rfe=RFE(estimator=SVR(kernel='linear'),n_features_to_select=2,step=1)
rfe.fit_transform(X,Y)

array([[-0.33503619,  0.07094626],
       [ 0.39547298,  0.61256458],
       [-1.0831359 , -0.40700687],
       [-1.36764927,  1.28028482],
       [-0.74728732,  1.2304945 ],
       [ 0.35810436, -0.55792615],
       [ 1.60160901,  0.48085873],
       [ 0.06773894, -0.076426  ],
       [ 2.28783927,  0.21120109],
       [ 0.43461304, -3.3209695 ]])

In [27]:
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)
sfm.fit_transform(X,Y)

array([[-0.33503619],
       [ 0.39547298],
       [-1.0831359 ],
       [-1.36764927],
       [-0.74728732],
       [ 0.35810436],
       [ 1.60160901],
       [ 0.06773894],
       [ 2.28783927],
       [ 0.43461304]])

In [29]:
#这里需注意下，threshold值越小，留下的数据越多，值越大，可能会去除完
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.001)
sfm.fit_transform(X,Y)

array([[-0.33503619],
       [ 0.39547298],
       [-1.0831359 ],
       [-1.36764927],
       [-0.74728732],
       [ 0.35810436],
       [ 1.60160901],
       [ 0.06773894],
       [ 2.28783927],
       [ 0.43461304]])

##特征变换--离散  对指化

In [30]:
#等深分箱
import numpy as np
import pandas as pd
lst=[6,8,10,15,16,24,25,40,67]
pd.qcut(lst,q=3)

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 24.333], (13.333, 24.333], (13.333, 24.333], (24.333, 67.0], (24.333, 67.0], (24.333, 67.0]]
Categories (3, interval[float64]): [(5.999, 13.333] < (13.333, 24.333] < (24.333, 67.0]]

In [31]:
pd.qcut(lst,q=3,labels=['low','medium','high'])

[low, low, low, medium, medium, medium, high, high, high]
Categories (3, object): [low < medium < high]

In [32]:
#等宽分箱
pd.cut(lst,bins=3)
pd.cut(lst,bins=3,labels=['low','medium','high'])

[low, low, low, low, low, low, low, medium, high]
Categories (3, object): [low < medium < high]

In [34]:
#引入归一化、标准化函数
from sklearn.preprocessing import MinMaxScaler,StandardScaler
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1,1)) #归一化

array([[0.  ],
       [0.15],
       [0.45],
       [0.7 ],
       [1.  ]])

In [35]:
#标准化
StandardScaler().fit_transform(np.array([1,1,1,1,0,0,0,0]).reshape(-1,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [36]:
StandardScaler().fit_transform(np.array([1,0,0,0,0,0,0,0]).reshape(-1,1))

array([[ 2.64575131],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

##数值化-标签和独热

In [38]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
LabelEncoder().fit_transform(np.array(['Down','Up','Down','Up']).reshape(-1,1))

d:\chen\biancheng\jupytertest\venv\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 1], dtype=int64)

In [39]:
LabelEncoder().fit_transform(np.array(['Low','Medium','High','Low','Medium']).reshape(-1,1))


array([1, 2, 0, 1, 2], dtype=int64)

In [40]:
lb_encoder=LabelEncoder()
lb_tran_f=lb_encoder.fit_transform(np.array(['Red','Yellow','Blue','Green']))
oht_encoder=OneHotEncoder().fit(lb_tran_f.reshape(-1,1))
#OneHotEncoder需要每个是一行的形式

In [43]:
#先fit再transform
oht_encoder.transform(lb_encoder.transform(np.array(['Red','Yellow','Blue','Green'])).reshape(-1,1))
#稀疏矩阵

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [44]:
#查看结果
oht_encoder.transform(lb_encoder.transform(np.array(['Red','Yellow','Blue','Green'])).reshape(-1,1)).toarray()

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [45]:
#正规化、规范化
import numpy as np
import pandas as pd
from sklearn.preprocessing import Normalizer
Normalizer(norm='l1').fit_transform(np.array([1,1,3,-1,2]).reshape(-1,1))


array([[ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.]])

In [46]:
#对行正规化--l1
Normalizer(norm='l1').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.125,  0.125,  0.375, -0.125,  0.25 ]])

In [47]:
#对l2正规化
Normalizer(norm='l2').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.25,  0.25,  0.75, -0.25,  0.5 ]])

##特征降维LDA-线性判别式分析

In [4]:
import numpy as np
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
X=np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
Y=np.array([1,1,1,2,2,2])
LinearDiscriminantAnalysis(n_components=1).fit_transform(X,Y)
#n_components=1降到一维，留下几个特征

array([[-1.73205081],
       [-1.73205081],
       [-3.46410162],
       [ 1.73205081],
       [ 1.73205081],
       [ 3.46410162]])

In [5]:
#当作判别器使用--fisher cassifier
LinearDiscriminantAnalysis(n_components=1).fit(X,Y)
clf=LinearDiscriminantAnalysis(n_components=1).fit(X,Y)
clf.predict([[0.8,1]])

array([2])